name: up fork

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
   - cron: 0 16 */2 * *

jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: hectorqin/reader
          target_repository: MXJNZ6/reader
          upstream_branch: master
          target_branch: master
          force: false
          tags: true
